#include "library.h"

#include "../symbols.h"
#include "../data.h"

blueprint_t entity_blueprint_hero = {
            { 0                                  ,          ID, 0, 0,                0 },
            { 1                                  , LEVEL_WIDTH, 0, 0,              274-7+1 },
            { 2                                  ,         MAP, DEFAULT,   0,       40 },
            { 3                                  ,         MAP, ANIMATION, 0,      100 },
            { 4                                  ,         MAP, BEHAVIOUR, 0,     1500 },
            { 5                                  ,         MAP, COLLISION, 0,     3000 },
            { 40                                 ,           0, 0, 0,               14 },
            { 40 + ENTITY_COMPONENT_ANIM_FRAME   ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_ANIM_TIMER   ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_ANIM_DELAY   ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_ANIM_LEN     ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_FRAME_X      ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_FRAME_Y      ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_FRAME_W      ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_FRAME_H      ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_HITBOX_X     ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_HITBOX_Y     ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_HITBOX_W     ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_HITBOX_H     ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_X_POS_DES    ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_Y_POS_DES    ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_X_VEL_DES    ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_Y_VEL_DES    ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_X_VEL        ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_Y_VEL        ,     DEFAULT, 0, 0,                0 },
            { 40 + ENTITY_COMPONENT_TEXTURE      ,     DEFAULT, 0, 0,  SPRITE_SKELETON },
            { 40 + ENTITY_COMPONENT_STATE        ,     DEFAULT, 0, 0,             IDLE },
            { 40 + ENTITY_COMPONENT_SHEET        ,     DEFAULT, 0, 0,  ENTITY_SKELETON }, 
            { 40 + ENTITY_COMPONENT_LAYER        ,     DEFAULT, 0, 0,     LAYER_SPRITE },
            { 40 + ENTITY_COMPONENT_BUFFER       ,     DEFAULT, 0, 0,                1 },
            { 40 + ENTITY_COMPONENT_COLLISIONABLE,     DEFAULT, 0, 0, COLLISION_BEHAVIOUR_NORMAL },
            { 40 + ENTITY_COMPONENT_DIR          ,     DEFAULT, 0, 0,                1 },
            { 40 + ENTITY_COMPONENT_PHASES       ,     DEFAULT, 0, 0,   PHASE_FLAG_ALL },
            { 100, METADATA, 4, IDLE,         110  },
            { 101, METADATA, 6, WALKING,      210  },
            { 102, METADATA, 3, JUMPING,      310  },
            { 103, METADATA, 1, FALLING_DOWN, 410  },
            { 104, METADATA, 1, PREJUMP,      510  },
              { 110, MAP   , IDLE, 0,     130  },
              { 111, MAP   , IDLE, 1,     140  },
              { 112, MAP   , IDLE, 2,     150  },
              { 113, MAP   , IDLE, 3,     160  },
                { 130,                                0,  0,  0,  0 },
                { 130 + ANIMATION_COMPONENT_OUTLINE,  2,  2, 33, 37 },
                { 130 + ANIMATION_COMPONENT_HITBOX,   0,  0, 33, 37 },
                { 130 + ANIMATION_COMPONENT_GRIP,     9, 10,  0, 10 },
                { 130 + ANIMATION_COMPONENT_HANDLE,   9, 10,  0, 10 },
                { 130 + ANIMATION_COMPONENT_DELAY,    0,  0,  0, 50 },
                { 140,                                0,  0,  0,  0 },
                { 140 + ANIMATION_COMPONENT_OUTLINE, 42,  2, 33, 37 },
                { 140 + ANIMATION_COMPONENT_HITBOX,   0,  0, 33, 37 },
                { 140 + ANIMATION_COMPONENT_GRIP,     9, 10,  0, 10 },
                { 140 + ANIMATION_COMPONENT_HANDLE,   9, 10,  0, 10 },
                { 140 + ANIMATION_COMPONENT_DELAY,    0,  0,  0, 20 },
                { 150,                                0,  0,  0,  0 },
                { 150 + ANIMATION_COMPONENT_OUTLINE,  2, 62, 33, 37 },
                { 150 + ANIMATION_COMPONENT_HITBOX,   0,  0, 33, 37 },
                { 150 + ANIMATION_COMPONENT_GRIP,     9, 10,  0, 10 },
                { 150 + ANIMATION_COMPONENT_HANDLE,   9, 10,  0, 10 },
                { 150 + ANIMATION_COMPONENT_DELAY,    0,  0,  0, 20 },
                { 160,                                0,  0,  0,  0 },
                { 160 + ANIMATION_COMPONENT_OUTLINE, 42, 62, 33, 37 },
                { 160 + ANIMATION_COMPONENT_HITBOX,   0,  0, 33, 37 },
                { 160 + ANIMATION_COMPONENT_GRIP,     9, 10,  0, 10 },
                { 160 + ANIMATION_COMPONENT_HANDLE,   9, 10,  0, 10 },
                { 160 + ANIMATION_COMPONENT_DELAY,    0,  0,  0,  5 },
              { 210, MAP   , WALKING, 0,     230  }, // map to frames
              { 211, MAP   , WALKING, 1,     240  },
              { 212, MAP   , WALKING, 2,     250  },
              { 213, MAP   , WALKING, 3,     260  },
              { 214, MAP   , WALKING, 4,     270  },
              { 215, MAP   , WALKING, 5,     280  },
                { 230,                                 0,  0,  0,  0 },
                { 230 + ANIMATION_COMPONENT_OUTLINE,   2,122,33, 37 },
                { 230 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 230 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 230 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 230 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  3 },
                { 240,                                 0,  0, 0,  0 },
                { 240 + ANIMATION_COMPONENT_OUTLINE,  42,122,33, 37 },
                { 240 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 240 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 240 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 240 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  3 },
                { 250,                                 0,  0, 0,  0 },
                { 250 + ANIMATION_COMPONENT_OUTLINE,   2,182,33, 37 },
                { 250 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 250 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 250 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 250 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  3 },
                { 260,                                 0,  0, 0,  0 },
                { 260 + ANIMATION_COMPONENT_OUTLINE,  42,182,33, 37 },
                { 260 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 260 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 260 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 260 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  3 },
                { 270,                                 0,  0, 0,  0 },
                { 270 + ANIMATION_COMPONENT_OUTLINE,   2,242,33, 37 },
                { 270 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 270 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 270 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 270 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  3 },
                { 280,                                 0,  0, 0,  0 },
                { 280 + ANIMATION_COMPONENT_OUTLINE,  42,242,33, 37 },
                { 280 + ANIMATION_COMPONENT_HITBOX,    0,  0,33, 37 },
                { 280 + ANIMATION_COMPONENT_GRIP,      9, 10, 0, 10 },
                { 280 + ANIMATION_COMPONENT_HANDLE,    9, 10, 0, 10 },
                { 280 + ANIMATION_COMPONENT_DELAY,     0,  0, 0,  5 },
              { 310, MAP   , JUMPING, 0, 330  },
              { 311, MAP   , JUMPING, 1, 340  },
              { 312, MAP   , JUMPING, 2, 350  },
                { 330,                                0,  0, 0,  0 },
                { 330 + ANIMATION_COMPONENT_OUTLINE, 42,304,33, 37 },
                { 330 + ANIMATION_COMPONENT_HITBOX,   0,  0,33, 37 },
                { 330 + ANIMATION_COMPONENT_GRIP,     9, 10, 0, 10 },
                { 330 + ANIMATION_COMPONENT_HANDLE,   9, 10, 0, 10 },
                { 330 + ANIMATION_COMPONENT_DELAY,    0,  0, 0,  3 },
                { 340,                                0,  0, 0,  0 },
                { 340 + ANIMATION_COMPONENT_OUTLINE,  2,364,33, 37 },
                { 340 + ANIMATION_COMPONENT_HITBOX,   0,  0,33, 37 },
                { 340 + ANIMATION_COMPONENT_GRIP,     9, 10, 0, 10 },
                { 340 + ANIMATION_COMPONENT_HANDLE,   9, 10, 0, 10 },
                { 340 + ANIMATION_COMPONENT_DELAY,    0,  0, 0,  3 },
                { 350,                                0,  0, 0,  0 },
                { 350 + ANIMATION_COMPONENT_OUTLINE, 42,364,33, 37 },
                { 350 + ANIMATION_COMPONENT_HITBOX,   0,  0,33, 37 },
                { 350 + ANIMATION_COMPONENT_GRIP,     9, 10, 0, 10 },
                { 350 + ANIMATION_COMPONENT_HANDLE,   9, 10, 0, 10 },
                { 350 + ANIMATION_COMPONENT_DELAY,    0,  0, 0,  3 },
              { 410, MAP   ,FALLING_DOWN, 0, 430  },
                { 430,                               0,  0, 0,  0 },
                { 430 + ANIMATION_COMPONENT_OUTLINE, 2,426,33, 37 },
                { 430 + ANIMATION_COMPONENT_HITBOX,  0,  0,33, 37 },
                { 430 + ANIMATION_COMPONENT_GRIP,    9, 10, 0, 10 },
                { 430 + ANIMATION_COMPONENT_HANDLE,  9, 10, 0, 10 },
                { 430 + ANIMATION_COMPONENT_DELAY,   0,  0, 0,  0 },
              { 510, MAP   , PREJUMP, 0, 530  },
                { 530,                               0,  0, 0,  0 },
                { 530 + ANIMATION_COMPONENT_OUTLINE,42,304,33, 37 },
                { 530 + ANIMATION_COMPONENT_HITBOX,  0,  0,33, 37 },
                { 530 + ANIMATION_COMPONENT_GRIP,    9, 10, 0, 10 },
                { 530 + ANIMATION_COMPONENT_HANDLE,  9, 10, 0, 10 },
                { 530 + ANIMATION_COMPONENT_DELAY,   0,  0, 0,  3 },
            { 1500, MAP, 0, IDLE,         1510  }, 
              { 1510, METADATA, 4, PHASE_INIT,      1520  },
              { 1511, METADATA, 3, PHASE_PRE,       1530  },
              { 1512, METADATA, 3, PHASE_UPDATE,    1540  },
              { 1513, METADATA, 4, PHASE_CONTROL,   1550  },
              { 1514, METADATA, 1, PHASE_COLLISION, 1560  },
              { 1515, METADATA, 4, PHASE_RESOLVE,   1570  },
              { 1516, METADATA, 1, PHASE_DRAW,      1580  },
                { 1520, BEHAVIOUR, PHASE_INIT, 0, BEHAVIOUR_SET_DEFAULTS   },
                { 1521, BEHAVIOUR, PHASE_INIT, 1, BEHAVIOUR_SET_FRAME      },
                { 1522, BEHAVIOUR, PHASE_INIT, 2, BEHAVIOUR_SET_HITBOX     },
                { 1523, BEHAVIOUR, PHASE_INIT, 3, BEHAVIOUR_BLOCK_INIT     },
                { 1530, BEHAVIOUR, PHASE_PRE, 0, BEHAVIOUR_SET_CAMERA      },
                { 1531, BEHAVIOUR, PHASE_PRE, 1, BEHAVIOUR_ADD_FRAME_TIMER },
                { 1532, BEHAVIOUR, PHASE_PRE, 2, BEHAVIOUR_CATCH_POS       },
                { 1540, BEHAVIOUR, PHASE_UPDATE, 0, BEHAVIOUR_ADD_GRAVITY        },
                { 1541, BEHAVIOUR, PHASE_UPDATE, 1, BEHAVIOUR_HORIZONTAL_FRICION },
                { 1542, BEHAVIOUR, PHASE_UPDATE, 2, BEHAVIOUR_SET_FRAME       },
                { 1550, BEHAVIOUR, PHASE_CONTROL, 0, BEHAVIOUR_CONTROL_JUMP    },
                { 1551, BEHAVIOUR, PHASE_CONTROL, 1, BEHAVIOUR_CONTROL_LEFT    },
                { 1552, BEHAVIOUR, PHASE_CONTROL, 2, BEHAVIOUR_CONTROL_RIGHT   },
                { 1553, BEHAVIOUR, PHASE_CONTROL, 3, BEHAVIOUR_UPDATE_VELOCITY },
                { 1560, BEHAVIOUR, PHASE_COLLISION, 0, BEHAVIOUR_CHECK_COLLISION },
                { 1570, BEHAVIOUR, PHASE_RESOLVE, 0, BEHAVIOUR_ADD_GRAVITY      },
                { 1571, BEHAVIOUR, PHASE_RESOLVE, 1, BEHAVIOUR_UPDATE_POSITION  },
                { 1572, BEHAVIOUR, PHASE_RESOLVE, 2, BEHAVIOUR_SET_FOCUS        },
                { 1573, BEHAVIOUR, PHASE_RESOLVE, 3, BEHAVIOUR_ANIM_FRAME       },
                { 1574, BEHAVIOUR, PHASE_RESOLVE, 4, BEHAVIOUR_UPDATE_SECTOR   },
                { 1580, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE   },
            { 1501, MAP, 0, WALKING,      1610  }, 
              { 1611, METADATA, 3, PHASE_PRE,       1620  },
              { 1612, METADATA, 3, PHASE_UPDATE,    1630  },
              { 1613, METADATA, 4, PHASE_CONTROL,   1640  },
              { 1614, METADATA, 1, PHASE_COLLISION, 1650  },
              { 1615, METADATA, 4, PHASE_RESOLVE,   1660  },
              { 1616, METADATA, 1, PHASE_DRAW,      1670  },
                { 1620, BEHAVIOUR, PHASE_PRE, 0, BEHAVIOUR_SET_CAMERA      },
                { 1621, BEHAVIOUR, PHASE_PRE, 1, BEHAVIOUR_ADD_FRAME_TIMER },
                { 1622, BEHAVIOUR, PHASE_PRE, 2, BEHAVIOUR_CATCH_POS       },
                { 1630, BEHAVIOUR, PHASE_UPDATE, 0, BEHAVIOUR_ADD_GRAVITY        },
                { 1631, BEHAVIOUR, PHASE_UPDATE, 1, BEHAVIOUR_HORIZONTAL_FRICION },
                { 1632, BEHAVIOUR, PHASE_UPDATE, 2, BEHAVIOUR_SET_FRAME },
                { 1640, BEHAVIOUR, PHASE_CONTROL, 0, BEHAVIOUR_CONTROL_JUMP    },
                { 1641, BEHAVIOUR, PHASE_CONTROL, 1, BEHAVIOUR_CONTROL_LEFT    },
                { 1642, BEHAVIOUR, PHASE_CONTROL, 2, BEHAVIOUR_CONTROL_RIGHT   },
                { 1643, BEHAVIOUR, PHASE_CONTROL, 3, BEHAVIOUR_UPDATE_VELOCITY },
                { 1650, BEHAVIOUR, PHASE_COLLISION, 0, BEHAVIOUR_CHECK_COLLISION },
                { 1660, BEHAVIOUR, PHASE_RESOLVE, 0, BEHAVIOUR_UPDATE_POSITION },
                { 1661, BEHAVIOUR, PHASE_RESOLVE, 1, BEHAVIOUR_SET_FOCUS       },
                { 1662, BEHAVIOUR, PHASE_RESOLVE, 2, BEHAVIOUR_ANIM_FRAME      },
                { 1663, BEHAVIOUR, PHASE_RESOLVE, 3, BEHAVIOUR_UPDATE_SECTOR   },
                { 1670, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE   },
            { 1502, MAP, 0, JUMPING,      1710  }, 
              { 1711, METADATA, 3, PHASE_PRE,       1720  },
              { 1712, METADATA, 3, PHASE_UPDATE,    1730  },
              { 1713, METADATA, 3, PHASE_CONTROL,   1740  },
              { 1714, METADATA, 2, PHASE_COLLISION, 1750  },
              { 1715, METADATA, 3, PHASE_RESOLVE,   1760  },
              { 1716, METADATA, 1, PHASE_DRAW,      1770  },
                { 1720, BEHAVIOUR, PHASE_PRE, 0, BEHAVIOUR_SET_CAMERA      },
                { 1721, BEHAVIOUR, PHASE_PRE, 1, BEHAVIOUR_ADD_FRAME_TIMER },
                { 1722, BEHAVIOUR, PHASE_PRE, 2, BEHAVIOUR_CATCH_POS       },
                { 1730, BEHAVIOUR, PHASE_UPDATE, 0, BEHAVIOUR_ADD_GRAVITY        },
                { 1731, BEHAVIOUR, PHASE_UPDATE, 1, BEHAVIOUR_HORIZONTAL_AIR_FRICION },
                { 1732, BEHAVIOUR, PHASE_UPDATE, 2, BEHAVIOUR_SET_FRAME },
                { 1740, BEHAVIOUR, PHASE_CONTROL, 0, BEHAVIOUR_CONTROL_LEFT    },
                { 1741, BEHAVIOUR, PHASE_CONTROL, 1, BEHAVIOUR_CONTROL_RIGHT   },
                { 1742, BEHAVIOUR, PHASE_CONTROL, 2, BEHAVIOUR_UPDATE_VELOCITY },
                { 1750, BEHAVIOUR, PHASE_COLLISION, 0, BEHAVIOUR_CHECK_COLLISION  },
                { 1751, BEHAVIOUR, PHASE_COLLISION, 1, BEHAVIOUR_CHECK_IF_FALLING },
                { 1760, BEHAVIOUR, PHASE_RESOLVE, 0, BEHAVIOUR_UPDATE_POSITION },
                { 1761, BEHAVIOUR, PHASE_RESOLVE, 1, BEHAVIOUR_SET_FOCUS       },
                { 1762, BEHAVIOUR, PHASE_RESOLVE, 2, BEHAVIOUR_ANIM_FRAME      },
                { 1763, BEHAVIOUR, PHASE_RESOLVE, 3, BEHAVIOUR_UPDATE_SECTOR   },
                { 1770, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE   },
            { 1503, MAP, 0, FALLING_DOWN, 1810  }, 
              { 1811, METADATA, 3, PHASE_PRE,       1820  },
              { 1812, METADATA, 4, PHASE_UPDATE,    1830  },
              { 1813, METADATA, 0, PHASE_CONTROL,   1840  },
              { 1814, METADATA, 1, PHASE_COLLISION, 1850  },
              { 1815, METADATA, 4, PHASE_RESOLVE,   1860  },
              { 1816, METADATA, 1, PHASE_DRAW,      1870  },
                { 1820, BEHAVIOUR, PHASE_PRE, 0, BEHAVIOUR_SET_CAMERA      },
                { 1821, BEHAVIOUR, PHASE_PRE, 1, BEHAVIOUR_ADD_FRAME_TIMER },
                { 1822, BEHAVIOUR, PHASE_PRE, 2, BEHAVIOUR_CATCH_POS       },
                { 1830, BEHAVIOUR, PHASE_UPDATE, 0, BEHAVIOUR_ADD_GRAVITY        },
                { 1831, BEHAVIOUR, PHASE_UPDATE, 1, BEHAVIOUR_HORIZONTAL_AIR_FRICION },
                { 1832, BEHAVIOUR, PHASE_UPDATE, 2, BEHAVIOUR_SET_FRAME },
                { 1833, BEHAVIOUR, PHASE_UPDATE, 3, BEHAVIOUR_UPDATE_VELOCITY },
                { 1850, BEHAVIOUR, PHASE_COLLISION, 0, BEHAVIOUR_CHECK_COLLISION },
                { 1860, BEHAVIOUR, PHASE_RESOLVE, 0, BEHAVIOUR_UPDATE_POSITION      },
                { 1861, BEHAVIOUR, PHASE_RESOLVE, 1, BEHAVIOUR_CHECK_IF_STOP_FALLING},
                { 1862, BEHAVIOUR, PHASE_RESOLVE, 2, BEHAVIOUR_SET_FOCUS            },
                { 1863, BEHAVIOUR, PHASE_RESOLVE, 3, BEHAVIOUR_UPDATE_SECTOR        },
                { 1870, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE   },
            { 1504, MAP, 0, PREJUMP,      1910  }, 
              { 1911, METADATA, 3, PHASE_PRE,       1920  },
              { 1912, METADATA, 1, PHASE_UPDATE,    1930  },
              { 1913, METADATA, 2, PHASE_CONTROL,   1940  },
              { 1914, METADATA, 1, PHASE_COLLISION, 1950  },
              { 1915, METADATA, 4, PHASE_RESOLVE,   1960  },
              { 1916, METADATA, 1, PHASE_DRAW,      1970  },
                { 1920, BEHAVIOUR, PHASE_PRE, 0, BEHAVIOUR_SET_CAMERA      },
                { 1921, BEHAVIOUR, PHASE_PRE, 1, BEHAVIOUR_ADD_FRAME_TIMER },
                { 1922, BEHAVIOUR, PHASE_PRE, 2, BEHAVIOUR_CATCH_POS       },
                { 1930, BEHAVIOUR, PHASE_UPDATE, 0, BEHAVIOUR_SET_FRAME },
                { 1940, BEHAVIOUR, PHASE_CONTROL, 0, BEHAVIOUR_CONTINUE_JUMP    },
                { 1941, BEHAVIOUR, PHASE_CONTROL, 1, BEHAVIOUR_UPDATE_VELOCITY },
                { 1950, BEHAVIOUR, PHASE_COLLISION, 0, BEHAVIOUR_CHECK_COLLISION },
                { 1960, BEHAVIOUR, PHASE_RESOLVE, 0, BEHAVIOUR_UPDATE_POSITION },
                { 1961, BEHAVIOUR, PHASE_RESOLVE, 1, BEHAVIOUR_SET_FOCUS       },
                { 1962, BEHAVIOUR, PHASE_RESOLVE, 2, BEHAVIOUR_ANIM_FRAME      },
                { 1963, BEHAVIOUR, PHASE_RESOLVE, 3, BEHAVIOUR_UPDATE_SECTOR   },
                { 1970, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE   },
            { 3000, MAP, COLLISION, IDLE,         3010  }, 
            { 3001, MAP, COLLISION, WALKING,      3020  }, 
            { 3002, MAP, COLLISION, JUMPING,      3030  }, 
            { 3003, MAP, COLLISION, FALLING_DOWN, 3040  }, 
            { 3004, MAP, COLLISION, PREJUMP,      3050  }, 
                { 3010, COLLISION, IDLE, COLLISION_BODY_SOLID, COLLISION_BEHAVIOUR_NORMAL         },
                { 3020, COLLISION, WALKING, COLLISION_BODY_SOLID, COLLISION_BEHAVIOUR_NORMAL      },
                { 3030, COLLISION, JUMPING, COLLISION_BODY_SOLID, COLLISION_BEHAVIOUR_NORMAL      },
                { 3040, COLLISION, FALLING_DOWN, COLLISION_BODY_SOLID, COLLISION_BEHAVIOUR_NORMAL },
                { 3050, COLLISION, PREJUMP, COLLISION_BODY_SOLID, COLLISION_BEHAVIOUR_NORMAL      }
    };

blueprint_t entity_blueprint_tile = {
        { 0, 12,          0, 0, 0         },
        { 1, LEVEL_WIDTH, 0, 0, 276-250+1 },
        { 2,         MAP, 0, 0, 40        },
        { 3,         MAP, 0, 0, -1        },
        { 4,         MAP, 0, 0, 500       },
        { 5,         MAP, 0, 0, -1        },
        { 40,                             0, 0, 0, 0,                                     },
        { 40 + ENTITY_COMPONENT_FRAME_X,  0, 0, 0, 0                                      },
        { 40 + ENTITY_COMPONENT_FRAME_Y,  0, 0, 0, 0                                      },
        { 40 + ENTITY_COMPONENT_FRAME_W,  0, 0, 0, 32                                     },
        { 40 + ENTITY_COMPONENT_FRAME_H,  0, 0, 0, 32                                     },
        { 40 + ENTITY_COMPONENT_DIR,      0, 0, 0, 0                                      },
        { 40 + ENTITY_COMPONENT_HITBOX_X, 0, 0, 0, 0                                      },
        { 40 + ENTITY_COMPONENT_HITBOX_Y, 0, 0, 0, 0                                      },
        { 40 + ENTITY_COMPONENT_HITBOX_W, 0, 0, 0, 32                                     },
        { 40 + ENTITY_COMPONENT_HITBOX_H, 0, 0, 0, 32                                     }, 
        { 40 + ENTITY_COMPONENT_TEXTURE,  0, 0, 0, SPRITE_TILE                            },
        { 40 + ENTITY_COMPONENT_SHEET,    0, 0, 0, ENTITY_TILE                            }, 
        { 40 + ENTITY_COMPONENT_LAYER,    0, 0, 0, LAYER_TILE                             },
        { 40 + ENTITY_COMPONENT_BUFFER,   0, 0, 0, 1                                      },
        { 40 + ENTITY_COMPONENT_PHASES,   0, 0, 0, PHASE_FLAG_INIT + PHASE_FLAG_DRAW      },
        { 500, MAP, 0, IDLE,         510  }, 
          { 510, METADATA, 2, PHASE_INIT,      520  }, // n + which phase
          { 516, METADATA, 1, PHASE_DRAW,      580  }, // n + which phase
            { 520, BEHAVIOUR, PHASE_INIT, 0, BEHAVIOUR_SET_DEFAULTS   },
            { 521, BEHAVIOUR, PHASE_INIT, 1, BEHAVIOUR_BLOCK_INIT     },
            { 580, BEHAVIOUR, PHASE_DRAW, 0, BEHAVIOUR_DRAW_SPRITE    }
    };

void BPT_create_entity_library(
) {
    int w;

    w = entity_blueprint_hero[1][4];
    BPT_serialize(entity_blueprint_hero, "./src/data/entites/hero", w);

    w = entity_blueprint_tile[1][4];
    BPT_serialize(entity_blueprint_tile, "./src/data/entites/tile", w);
}
